- name: /etc/cosmos-validator-exporter 디렉토리 생성
  file:
    path: /etc/cosmos-validator-exporter
    state: directory
    mode: "0755"
  tags: exporter

- name: config.toml 템플릿 배포
  template:
    src: config.toml.j2
    dest: /etc/cosmos-validator-exporter/config.toml
    mode: "0644"
  tags: exporter

- name: Exporter 설치 디렉토리 생성
  file:
    path: /opt/cosmos-validator-exporter
    state: directory
    mode: "0755"
  tags: exporter

- name: Exporter 바이너리 다운로드
  get_url:
    url: "https://github.com/QuokkaStake/cosmos-validators-exporter/releases/download/v7.0.3/cosmos-validators-exporter_7.0.3_linux_amd64.tar.gz"
    dest: /opt/cosmos-validator-exporter/cosmos-validators-exporter.tar.gz
  tags: exporter

- name: 압축 해제 (우분투 원격에서)
  unarchive:
    src: /opt/cosmos-validator-exporter/cosmos-validators-exporter.tar.gz
    dest: /opt/cosmos-validator-exporter/
    remote_src: yes
    extra_opts: [--strip-components=1]
  tags: exporter

- name: 실행 파일 시스템 경로로 복사
  copy:
    src: /opt/cosmos-validator-exporter/cosmos-validators-exporter
    dest: /usr/local/bin/cosmos-validators-exporter
    mode: "0755"
    remote_src: yes
  tags: exporter

- name: systemd 유닛 템플릿 배포
  template:
    src: cosmos-validator-exporter.service.j2
    dest: /etc/systemd/system/cosmos-validator-exporter.service
    mode: "0644"
  tags: exporter

- name: systemd 데몬 리로드
  command: systemctl daemon-reload
  tags: exporter

- name: Exporter 서비스 등록 및 실행
  systemd:
    name: cosmos-validator-exporter
    state: started
    enabled: yes
  tags: exporter
