- name: "[5단계] 블록 제안 타임아웃 설정 (timeout_propose)"
  lineinfile:
    path: "{{ simd_home }}/config/config.toml"
    regexp: '^timeout_propose ='
    line: 'timeout_propose = "100ms"'

- name: "[5단계] Prevote 타임아웃 설정 (timeout_prevote)"
  lineinfile:
    path: "{{ simd_home }}/config/config.toml"
    regexp: '^timeout_prevote ='
    line: 'timeout_prevote = "100ms"'

- name: "[5단계] Precommit 타임아웃 설정 (timeout_precommit)"
  lineinfile:
    path: "{{ simd_home }}/config/config.toml"
    regexp: '^timeout_precommit ='
    line: 'timeout_precommit = "100ms"'

- name: "[5단계] 블록 생성 주기 설정 (timeout_commit = 500ms)"
  lineinfile:
    path: "{{ simd_home }}/config/config.toml"
    regexp: '^timeout_commit ='
    line: 'timeout_commit = "500ms"'

- name: "[5단계] Prometheus 메트릭 수집 활성화"
  lineinfile:
    path: "{{ simd_home }}/config/config.toml"
    regexp: '^prometheus ='
    line: 'prometheus = true'
    insertafter: '^\[instrumentation\]'
  tags: update-config

- name: "[5단계] laddr의 IP만 0.0.0.0으로 덮어쓰기 (포트 유지)"
  replace:
    path: "{{ simd_home }}/config/config.toml"
    regexp: '^laddr = "tcp://[^:]+:(\d+)"'
    replace: 'laddr = "tcp://0.0.0.0:\1"'
  tags: update-config

- name: "[5단계] app.toml 배포"
  template:
    src: app.toml.j2
    dest: "{{ simd_home }}/config/app.toml"
    mode: "0644"
    owner: ubuntu
    group: ubuntu
  tags: update-config
