- name: 공통 설정
  hosts: validators
  become: yes
  roles:
    - common

- name: Cosmos 체인 초기화 및 실행
  hosts: validators
  become: yes
  roles:
    - chain-init
    - make-key
    - genesis-gentx
    - copy-genesis
    - update-config
    - start-node

- name : cosmos-validator-exporter 실행
  hosts: validators
  become: yes
  roles:
    - exporter