- name: "[3단계] 서울 노드에서 SE_ADDR에 잔액 등록"
  when: inventory_hostname == "seoul"
  command: >
    {{ simd_bin }} add-genesis-account {{ SE_ADDR }} {{ stake_amount }}{{ stake_denom }}
    --home {{ simd_home }}
  environment: "{{ env_simd }}"

- name: "[3단계] 서울 노드에서 TK_ADDR에 잔액 등록"
  when: inventory_hostname == "seoul"
  command: >
    {{ simd_bin }} add-genesis-account {{ TK_ADDR }} {{ stake_amount }}{{ stake_denom }}
    --home {{ simd_home }}
  environment: "{{ env_simd }}"

- name: "[3단계] 도쿄 노드 .simd-tokyo 디렉토리 권한/소유자 수정"
  when: inventory_hostname == "tokyo"
  file:
    path: /home/ubuntu/.simd-tokyo
    owner: ubuntu
    group: ubuntu
    mode: '0755'
    recurse: yes

- name: "[3단계] genesis.json 권한 수정 (ubuntu가 읽을 수 있도록)"
  when: inventory_hostname == "seoul"
  file:
    path: /home/ubuntu/.simd-seoul/config/genesis.json
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: "[3단계] 서울 genesis.json을 도쿄로 복사"
  when: inventory_hostname == "seoul"
  shell: |
    scp -i /home/ubuntu/node_2.pem \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        /home/ubuntu/.simd-seoul/config/genesis.json \
        ubuntu@52.196.214.161:/home/ubuntu/.simd-tokyo/config/genesis.json

- name: "[3단계] 각 노드 gentx 생성"
  command: >
    {{ simd_bin }} gentx {{ key_name }} {{ gentx_amount }}{{ stake_denom }}
      --chain-id {{ chain_id }}
      --home {{ simd_home }}
      --keyring-backend test
      --from {{ key_name }}
      -y
  environment: "{{ env_simd }}"

- name: "[3단계] 도쿄 gentx 파일을 서울로 전송 (도쿄 노드 전용)"
  when: inventory_hostname == "tokyo"
  shell: >
    scp -i /home/ubuntu/node_1.pem \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        {{ simd_home }}/config/gentx/*.json \
        ubuntu@3.35.221.3:/home/ubuntu/.simd-seoul/config/gentx/

- name: "[3단계] 서울 노드에서 gentx 수집"
  when: inventory_hostname == "seoul"
  command: >
    {{ simd_bin }} collect-gentxs
      --home {{ simd_home }}
      --gentx-dir {{ simd_home }}/config/gentx
  environment: "{{ env_simd }}"
  run_once: true

- name: "[3단계] 서울 genesis.json을 도쿄로 복사"
  when: inventory_hostname == "seoul"
  shell: |
    scp -i /home/ubuntu/node_2.pem \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        /home/ubuntu/.simd-seoul/config/genesis.json \
        ubuntu@52.196.214.161:/home/ubuntu/.simd-tokyo/config/genesis.json