- name: "[4단계] 각 노드의 node_id 추출"
  command: "{{ simd_bin }} tendermint show-node-id --home {{ simd_home }}"
  register: node_id_output
  changed_when: false

- name: "[4단계] this_node_id 팩트로 저장"
  set_fact:
    this_node_id: "{{ node_id_output.stdout }}"

# 서울 호스트면 seoul_node_id 팩트로, tokyo 호스트면 tokyo_node_id 팩트로 저장
- name: "[4단계] 호스트별 node_id 팩트 등록"
  set_fact:
    seoul_node_id: "{{ this_node_id }}"
  when: inventory_hostname == 'seoul'

- name: "[4단계] 호스트별 node_id 팩트 등록"
  set_fact:
    tokyo_node_id: "{{ this_node_id }}"
  when: inventory_hostname == 'tokyo'

- name: "[4단계] persistent_peers 한 줄로 대체"
  replace:
    path: "{{ simd_home }}/config/config.toml"
    regexp: '^persistent_peers =.*'
    replace: >-
      persistent_peers = "{{ (inventory_hostname == 'seoul') 
        | ternary(hostvars['tokyo'].tokyo_node_id, hostvars['seoul'].seoul_node_id) 
      }}@{{ peer_ip }}:26656"
  become: yes