- name: "[1단계] 기존 simd 홈 디렉토리 삭제"
  file:
    path: "{{ simd_home }}"
    state: absent

- name: "[1단계] simd 홈 디렉토리 재생성"
  file:
    path: "{{ simd_home }}"
    state: directory
    mode: '0755'
    owner: ubuntu
    group: ubuntu

- name: "[1단계] simd init 실행"
  command: >
    /home/ubuntu/go/bin/simd init {{ moniker }} --chain-id {{ chain_id }} --home {{ simd_home }}
  environment: "{{ env_simd }}"

- name: "[1단계] 기존 keyring 삭제 (ubuntu key)"
  file:
    path: "/home/ubuntu/.simd/keyring-test"
    state: absent
  ignore_errors: true

- name: "[1단계] config 디렉토리 소유자 ubuntu로 설정"
  file:
    path: "{{ simd_home }}/config"
    owner: ubuntu
    group: ubuntu
    recurse: yes

- name: "[1단계] 서울 노드에서 .simd-seoul gentx 디렉토리 삭제"
  when: inventory_hostname == "seoul"
  file:
    path: "/home/ubuntu/.simd-seoul/config/gentx"
    state: absent
  ignore_errors: true

- name: "[1단계] 서울 노드에서 .simd-tokyo gentx 디렉토리 삭제"
  when: inventory_hostname == "seoul"
  file:
    path: "/home/ubuntu/.simd-tokyo/config/gentx"
    state: absent
  ignore_errors: true


- name: "[1단계] gentx 디렉토리 재생성"
  file:
    path: "{{ simd_home }}/config/gentx"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
