# tasks.yml

- name: "[1단계] 기존 config 디렉토리 삭제"
  file:
    path: "{{ simd_home }}/config"
    state: absent
  become: yes

- name: "[1단계] 기존 data 디렉토리 삭제"
  file:
    path: "{{ simd_home }}/data"
    state: absent
  become: yes

- name: "[1단계] simd 홈 디렉토리 재생성"
  file:
    path: "{{ simd_home }}"
    state: directory
    mode: '0755'
    owner: ubuntu
    group: ubuntu
  become: yes

- name: "[1단계] simd init 실행"
  command: >
    {{ simd_bin }} init {{ moniker }}
      --chain-id {{ chain_id }}
      --home {{ simd_home }}
  environment: "{{ env_simd }}"
  become: yes

- name: "[1단계] simd_home 전체 소유권을 ubuntu로 설정"
  file:
    path: "{{ simd_home }}"
    recurse: yes
    owner: ubuntu
    group: ubuntu
  become: yes

- name: "[1단계] gentx 디렉토리 재생성"
  file:
    path: "{{ simd_home }}/config/gentx"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
  become: yes
